#系统配置
server:
  port: 80
#springboot配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hedgehog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    cache: false
  data:
    solr:
      host: http://localhost:8983/solr

com:
  qiniu:
    accessKey: G3wrnnkbDiMDYZLovFQF6DmaV1BLikj_NsIUAzul
    secretKey: Pk5cGZ5KQsv72cpFOCtSsRDUlDziHFmIoBp4OjaF
